"""价格审核业务常量。"""

EXHIBITION_CENTER_MEIJIANG = 0
EXHIBITION_CENTER_NEC = 1

EXHIBITION_CENTER_CHOICES = (
    (EXHIBITION_CENTER_MEIJIANG, "天津梅江会展中心"),
    (EXHIBITION_CENTER_NEC, "天津国家会展中心"),
)
EXHIBITION_CENTER_LABELS = dict(EXHIBITION_CENTER_CHOICES)

PROJECT_NATURE_TEMPORARY = 0
PROJECT_NATURE_PERMANENT = 1

PROJECT_NATURE_CHOICES = (
    (PROJECT_NATURE_TEMPORARY, "临时展会"),
    (PROJECT_NATURE_PERMANENT, "常设陈列"),
)
PROJECT_NATURE_LABELS = dict(PROJECT_NATURE_CHOICES)
