# Generated by Django 5.2.8 on 2025-12-06 23:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_name', models.CharField(help_text='批次展示名称，通常为目录名，例如“2025教育局专项资金第一批”。', max_length=255, unique=True, verbose_name='批次名称')),
                ('description', models.TextField(blank=True, help_text='可选说明信息，用于描述本批次的来源或用途。', null=True, verbose_name='批次说明')),
                ('status', models.CharField(choices=[('pending', '排队中'), ('processing', '处理中'), ('completed', '已完成'), ('failed', '失败')], db_index=True, default='pending', help_text='批次当前的处理状态：排队中/处理中/已完成/失败。', max_length=20, verbose_name='状态')),
                ('total_files', models.PositiveIntegerField(default=0, help_text='该批次包含的文件总数。', verbose_name='文件总数')),
                ('completed_files', models.PositiveIntegerField(default=0, help_text='审核已完成的文件数量。', verbose_name='已完成文件数')),
                ('failed_files', models.PositiveIntegerField(default=0, help_text='审核失败的文件数量。', verbose_name='失败文件数')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='批次创建时间。', verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='批次最近一次状态更新的时间。', verbose_name='更新时间')),
                ('created_by', models.ForeignKey(blank=True, help_text='发起本次批量审核的用户。', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_batches', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '审核批次',
                'verbose_name_plural': '审核批次',
                'db_table': 'indicator_audit_batch',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='AuditFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_filename', models.CharField(help_text='上传时的原始 Excel 文件名。', max_length=255, verbose_name='原始文件名')),
                ('relative_path', models.CharField(blank=True, help_text='文件夹内的相对路径，用于批次内断点续传与文件匹配。', max_length=512, null=True, verbose_name='相对路径')),
                ('file_size', models.BigIntegerField(blank=True, help_text='文件大小（字节）。', null=True, verbose_name='文件大小')),
                ('file_hash', models.CharField(db_index=True, help_text='文件内容指纹（如 SHA256），用于跨批次结果复用与去重。', max_length=64, verbose_name='文件指纹')),
                ('status', models.CharField(choices=[('pending', '排队中'), ('processing', '处理中'), ('completed', '已完成'), ('failed', '失败'), ('skipped', '已跳过')], db_index=True, default='pending', help_text='文件审核状态：排队中/处理中/已完成/失败/已跳过。', max_length=20, verbose_name='处理状态')),
                ('project_name', models.CharField(blank=True, help_text='从结构化数据中提取的项目名称，便于列表展示与检索。', max_length=255, null=True, verbose_name='项目名称')),
                ('department', models.CharField(blank=True, help_text='项目所属主管预算部门。', max_length=255, null=True, verbose_name='主管部门')),
                ('score', models.IntegerField(blank=True, help_text='该文件审核结果的健康分（0-100），来自审核报告。', null=True, verbose_name='健康分')),
                ('critical_count', models.PositiveIntegerField(default=0, help_text='该文件中红灯（critical）问题数量。', verbose_name='红灯数量')),
                ('warning_count', models.PositiveIntegerField(default=0, help_text='该文件中黄灯（warning）问题数量。', verbose_name='黄灯数量')),
                ('info_count', models.PositiveIntegerField(default=0, help_text='该文件中蓝灯（info）提示数量。', verbose_name='蓝灯数量')),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, help_text='该项目的资金总额（万元），可从结构化数据中提取。', max_digits=18, null=True, verbose_name='项目总金额')),
                ('pydantic_json', models.JSONField(blank=True, help_text='原始结构化数据（PerformanceDeclarationSchema）序列化后的 JSON。', null=True, verbose_name='结构化数据')),
                ('report_json', models.JSONField(blank=True, help_text='标准化后的审核报告 JSON，对应前端展示的数据结构。', null=True, verbose_name='审核报告')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='文件记录创建时间（上传时间）。', verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='文件记录最近一次更新的时间。', verbose_name='更新时间')),
                ('batch', models.ForeignKey(blank=True, help_text='所属审核批次，为空表示独立文件审核。', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='files', to='indicator_audit.auditbatch', verbose_name='所属批次')),
                ('reused_from_file', models.ForeignKey(blank=True, help_text='如果本次结果复用了历史审核结果，这里指向原始文件记录。', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reused_by_files', to='indicator_audit.auditfile', verbose_name='复用来源文件')),
            ],
            options={
                'verbose_name': '审核文件',
                'verbose_name_plural': '审核文件',
                'db_table': 'indicator_audit_file',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='AuditIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity', models.CharField(choices=[('critical', '红灯'), ('warning', '黄灯'), ('info', '蓝灯')], db_index=True, help_text='问题严重程度：红灯/黄灯/蓝灯。', max_length=16, verbose_name='严重程度')),
                ('source', models.CharField(help_text='问题来源：rules（刚性规则）/ai（语义审查）/system（系统）。', max_length=20, verbose_name='来源')),
                ('source_label', models.CharField(blank=True, help_text='来源中文标签，如“刚性规则”“智能审查”“系统”。', max_length=32, null=True, verbose_name='来源标签')),
                ('type', models.CharField(blank=True, choices=[('completeness', '完整性缺失'), ('compliance', '合规性问题'), ('measurability', '可衡量性不足'), ('relevance', '相关性缺失'), ('mismatch', '投入产出不匹配')], db_index=True, help_text='业务问题类型：完整性缺失 / 合规性问题 / 可衡量性不足 / 相关性缺失 / 投入产出不匹配。', max_length=32, null=True, verbose_name='问题类型')),
                ('title', models.CharField(help_text='问题的简短标题，便于列表快速浏览。', max_length=255, verbose_name='标题')),
                ('description', models.TextField(blank=True, help_text='问题的详细说明或判定依据。', null=True, verbose_name='问题描述')),
                ('position', models.CharField(blank=True, help_text='问题所在位置，例如“项目资金”“指标：系统验收合格率”等。', max_length=255, null=True, verbose_name='定位信息')),
                ('suggestion', models.TextField(blank=True, help_text='针对该问题的整改建议或优化意见。', null=True, verbose_name='整改建议')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='问题记录生成时间。', verbose_name='创建时间')),
                ('file', models.ForeignKey(help_text='该问题所属的 Excel 文件。', on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='indicator_audit.auditfile', verbose_name='所属文件')),
            ],
            options={
                'verbose_name': '审核问题',
                'verbose_name_plural': '审核问题',
                'db_table': 'indicator_audit_issue',
                'ordering': ('-created_at',),
            },
        ),
    ]
