# Generated by Django 5.2.8 on 2025-12-07 00:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicator_audit', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='auditfile',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='发起本次审核的用户。', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_files', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
    ]
