# Generated by Django 5.2.8 on 2025-11-14 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FundUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('source_file', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Indicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_1', models.CharField(max_length=255)),
                ('level_2', models.CharField(max_length=255)),
                ('level_3', models.CharField(max_length=255)),
                ('explanation', models.TextField(blank=True, null=True)),
                ('nature', models.CharField(max_length=255)),
                ('unit', models.CharField(max_length=255)),
                ('source', models.CharField(max_length=255)),
                ('is_vectorized', models.BooleanField(default=False)),
                ('fund_usage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicators', to='indicators.fundusage')),
            ],
        ),
    ]
