# Generated by Django 5.2.8 on 2025-11-15 02:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indicator',
            name='source',
        ),
        migrations.AddField(
            model_name='indicator',
            name='province',
            field=models.CharField(default='', help_text='数据来源或发布主体，例如“天津市”“广东省”。', max_length=10, verbose_name='指标省份'),
        ),
        migrations.AlterField(
            model_name='fundusage',
            name='name',
            field=models.CharField(help_text='资金使用类别名称，例如“信息系统建设运维类”。', max_length=255, verbose_name='资金使用类别名称'),
        ),
        migrations.AlterField(
            model_name='fundusage',
            name='source_file',
            field=models.CharField(blank=True, help_text='可选：标记该类别来自哪一个 CSV 或外部文件。', max_length=255, null=True, verbose_name='来源文件'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='explanation',
            field=models.TextField(blank=True, help_text='指标解释或补充说明，可为空。', null=True, verbose_name='指标解释'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='fund_usage',
            field=models.ForeignKey(help_text='该指标所属的资金使用类别。', on_delete=django.db.models.deletion.CASCADE, related_name='indicators', to='indicators.fundusage', verbose_name='资金使用类别'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='is_vectorized',
            field=models.BooleanField(default=False, help_text='是否已向量化（由脚本维护，后台仅展示）。', verbose_name='是否向量化'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='level_1',
            field=models.CharField(help_text='一级指标分类，例如“产出指标”。', max_length=255, verbose_name='一级指标'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='level_2',
            field=models.CharField(help_text='二级指标分类，例如“质量指标”。', max_length=255, verbose_name='二级指标'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='level_3',
            field=models.CharField(help_text='三级指标名称，如“系统验收合格率”。', max_length=255, verbose_name='三级指标'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='nature',
            field=models.CharField(help_text='指标的性质或比较符号，例如“≥”“≤”“定性描述”。', max_length=255, verbose_name='指标性质'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='unit',
            field=models.CharField(help_text='指标计量单位，如“%”“个”“万元”。', max_length=20, verbose_name='计量单位'),
        ),
    ]
