# Generated by Django 5.2.8 on 2025-11-15 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("indicators", "0003_indicator_province_fk"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="fundusage",
            options={
                "verbose_name": "资金用途/项目",
                "verbose_name_plural": "资金用途/项目",
            },
        ),
        migrations.AlterModelOptions(
            name="indicator",
            options={"verbose_name": "指标库", "verbose_name_plural": "指标库"},
        ),
        migrations.AddField(
            model_name="indicator",
            name="is_active",
            field=models.BooleanField(
                db_index=True,
                default=True,
                help_text="软删除标记，False 代表在最新同步中未启用。",
                verbose_name="是否启用",
            ),
        ),
        migrations.AddField(
            model_name="indicator",
            name="source_tag",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="用于记录导入来源或批次的标签。",
                max_length=255,
                null=True,
                verbose_name="数据来源/批次",
            ),
        ),
    ]
