# Generated by Django 5.2.8 on 2025-11-15 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("indicators", "0004_alter_fundusage_options_alter_indicator_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="indicator",
            name="business_code",
            field=models.CharField(
                blank=True,
                help_text="业务编码或唯一标识，可为空。",
                max_length=255,
                null=True,
                verbose_name="编码",
            ),
        ),
    ]
