# Generated by Django 5.2.8 on 2025-11-16 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("indicators", "0005_indicator_business_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="indicator",
            name="level_1",
            field=models.CharField(
                blank=True,
                help_text="一级指标分类，例如“产出指标”。",
                max_length=255,
                verbose_name="一级指标",
            ),
        ),
        migrations.AlterField(
            model_name="indicator",
            name="level_2",
            field=models.CharField(
                blank=True,
                help_text="二级指标分类，例如“质量指标”。",
                max_length=255,
                verbose_name="二级指标",
            ),
        ),
        migrations.AlterField(
            model_name="indicator",
            name="nature",
            field=models.CharField(
                blank=True,
                help_text="指标的性质或比较符号，例如“≥”“≤”“定性描述”。",
                max_length=255,
                verbose_name="指标性质",
            ),
        ),
        migrations.AlterField(
            model_name="indicator",
            name="unit",
            field=models.CharField(
                blank=True,
                help_text="指标计量单位，如“%”“个”“万元”。",
                max_length=20,
                verbose_name="计量单位",
            ),
        ),
    ]
