# Generated by Django 5.2.8 on 2025-11-19 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0006_alter_indicator_level_1_alter_indicator_level_2_and_more'),
        ('regions', '0001_populate_regions'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundusage',
            name='province',
            field=models.ForeignKey(blank=True, help_text='该资金用途所属省份。', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fund_usages', to='regions.province', verbose_name='所属省份'),
        ),
        migrations.AddConstraint(
            model_name='fundusage',
            constraint=models.UniqueConstraint(fields=('province', 'name'), name='unique_fund_usage_province_name'),
        ),
    ]
