# Generated by Django 5.2.8 on 2026-03-07 15:18

import django.db.models.deletion
import price_audit.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GovernmentPriceBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_name', models.CharField(db_index=True, max_length=100, verbose_name='地区')),
                ('year', models.PositiveIntegerField(db_index=True, verbose_name='年份')),
                ('source_file', models.FileField(blank=True, upload_to=price_audit.models.government_price_source_upload_to, verbose_name='源文件')),
                ('source_filename', models.CharField(blank=True, max_length=255, verbose_name='原始文件名')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='是否生效')),
                ('total_rows', models.PositiveIntegerField(default=0, verbose_name='总行数')),
                ('success_rows', models.PositiveIntegerField(default=0, verbose_name='有效行数')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('template_version', models.CharField(default='v1', max_length=20, verbose_name='模板版本')),
                ('deactivated_at', models.DateTimeField(blank=True, null=True, verbose_name='失效时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('replaced_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replacement_batches', to='price_audit.governmentpricebatch', verbose_name='被替换批次')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='government_price_batches', to=settings.AUTH_USER_MODEL, verbose_name='上传人')),
            ],
            options={
                'verbose_name': '政府标准价批次',
                'verbose_name_plural': '政府标准价批次',
                'db_table': 'price_audit_government_price_batch',
                'ordering': ('-year', 'region_name', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='GovernmentPriceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_no', models.PositiveIntegerField(verbose_name='Excel 行号')),
                ('material_name_raw', models.CharField(max_length=255, verbose_name='材料名称')),
                ('material_name_normalized', models.CharField(db_index=True, max_length=255, verbose_name='材料名称标准化')),
                ('spec_model_raw', models.CharField(blank=True, max_length=255, verbose_name='规格型号')),
                ('spec_model_normalized', models.CharField(blank=True, db_index=True, max_length=255, verbose_name='规格型号标准化')),
                ('unit_raw', models.CharField(blank=True, max_length=50, verbose_name='单位')),
                ('unit_normalized', models.CharField(blank=True, db_index=True, max_length=50, verbose_name='单位标准化')),
                ('benchmark_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='中准价格')),
                ('price_min', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='区间最低价')),
                ('price_max', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='区间最高价')),
                ('description', models.TextField(blank=True, verbose_name='说明')),
                ('is_tax_included', models.BooleanField(default=True, verbose_name='是否含税')),
                ('raw_row_data', models.JSONField(blank=True, default=dict, verbose_name='原始行数据')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='price_audit.governmentpricebatch', verbose_name='所属批次')),
            ],
            options={
                'verbose_name': '政府标准价明细',
                'verbose_name_plural': '政府标准价明细',
                'db_table': 'price_audit_government_price_item',
                'ordering': ('batch_id', 'row_no'),
                'constraints': [models.UniqueConstraint(fields=('batch', 'row_no'), name='uniq_government_price_item_batch_row_no')],
            },
        ),
    ]
