# Generated by Django 5.2.8 on 2026-03-08 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price_audit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='governmentpricebatch',
            name='last_error',
            field=models.TextField(blank=True, verbose_name='最后错误'),
        ),
        migrations.AddField(
            model_name='governmentpricebatch',
            name='vector_failed',
            field=models.PositiveIntegerField(default=0, verbose_name='向量化失败数'),
        ),
        migrations.AddField(
            model_name='governmentpricebatch',
            name='vector_status',
            field=models.CharField(choices=[('pending_vectorization', '待向量化'), ('vectorizing', '向量化中'), ('active', '可用于审核'), ('vector_failed', '向量化失败')], db_index=True, default='pending_vectorization', max_length=32, verbose_name='向量状态'),
        ),
        migrations.AddField(
            model_name='governmentpricebatch',
            name='vector_success',
            field=models.PositiveIntegerField(default=0, verbose_name='向量化成功数'),
        ),
        migrations.AddField(
            model_name='governmentpricebatch',
            name='vector_total',
            field=models.PositiveIntegerField(default=0, verbose_name='待向量化总数'),
        ),
        migrations.AddField(
            model_name='governmentpricebatch',
            name='vectorized_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='向量化完成时间'),
        ),
    ]
