# Generated by Django 5.2.8 on 2026-03-08 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price_audit', '0002_governmentpricebatch_last_error_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='governmentpricebatch',
            name='vector_queued_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='入队时间'),
        ),
        migrations.AddField(
            model_name='governmentpricebatch',
            name='vector_started_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='开始执行时间'),
        ),
        migrations.AddField(
            model_name='governmentpricebatch',
            name='vector_task_id',
            field=models.CharField(blank=True, db_index=True, max_length=64, verbose_name='Celery任务ID'),
        ),
    ]
