# Generated by Django 5.2.8 on 2026-03-08 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price_audit', '0003_governmentpricebatch_vector_queued_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='governmentpriceitem',
            name='embedding_text',
            field=models.CharField(blank=True, max_length=1024, verbose_name='向量文本'),
        ),
        migrations.AddField(
            model_name='governmentpriceitem',
            name='is_vectorized',
            field=models.BooleanField(db_index=True, default=False, verbose_name='是否已向量化'),
        ),
    ]
