# Generated by Django 5.2.8 on 2026-03-11 04:07

import django.db.models.deletion
import price_audit.models.common
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price_audit', '0004_governmentpriceitem_embedding_text_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceAuditSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_filename', models.CharField(max_length=255, verbose_name='原始文件名')),
                ('project_name', models.CharField(blank=True, max_length=255, verbose_name='项目名称')),
                ('source_file', models.FileField(upload_to=price_audit.models.common.price_audit_submission_source_upload_to, verbose_name='送审文件')),
                ('audited_excel_file', models.FileField(blank=True, upload_to=price_audit.models.common.price_audit_submission_audited_excel_upload_to, verbose_name='审核表文件')),
                ('status', models.CharField(choices=[('pending', '排队中'), ('processing', '处理中'), ('completed', '已完成'), ('failed', '失败')], db_index=True, default='pending', max_length=20, verbose_name='状态')),
                ('submitted_total_amount', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True, verbose_name='送审总金额')),
                ('reviewed_total_amount', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True, verbose_name='审核总金额')),
                ('reduction_total_amount', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True, verbose_name='审减总金额')),
                ('report_json', models.JSONField(blank=True, default=dict, verbose_name='审核报告')),
                ('error_message', models.TextField(blank=True, verbose_name='错误信息')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='price_audit_submissions', to=settings.AUTH_USER_MODEL, verbose_name='上传人')),
                ('price_batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submissions', to='price_audit.governmentpricebatch', verbose_name='使用标准价批次')),
            ],
            options={
                'verbose_name': '价格送审单',
                'verbose_name_plural': '价格送审单',
                'db_table': 'price_audit_submission',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='PriceAuditSubmissionRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('excel_row_no', models.PositiveIntegerField(verbose_name='Excel 行号')),
                ('sequence_no', models.CharField(blank=True, max_length=32, verbose_name='序号')),
                ('parent_sequence_no', models.CharField(blank=True, max_length=32, verbose_name='父级序号')),
                ('row_type', models.CharField(choices=[('leaf', '明细行'), ('group', '父项汇总行'), ('summary', '汇总行')], db_index=True, default='leaf', max_length=16, verbose_name='行类型')),
                ('fee_type', models.CharField(max_length=255, verbose_name='费用类型')),
                ('submitted_unit', models.CharField(blank=True, max_length=32, verbose_name='送审单位')),
                ('submitted_unit_price', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True, verbose_name='送审单价')),
                ('submitted_quantity', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True, verbose_name='送审数量')),
                ('submitted_days', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True, verbose_name='送审天数')),
                ('submitted_amount', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True, verbose_name='送审金额')),
                ('budget_note', models.TextField(blank=True, verbose_name='预算说明')),
                ('raw_row_data', models.JSONField(blank=True, default=dict, verbose_name='原始行数据')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='price_audit.priceauditsubmission', verbose_name='所属送审单')),
            ],
            options={
                'verbose_name': '价格送审明细行',
                'verbose_name_plural': '价格送审明细行',
                'db_table': 'price_audit_submission_row',
                'ordering': ('submission_id', 'excel_row_no'),
            },
        ),
        migrations.CreateModel(
            name='PriceAuditRowDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', '排队中'), ('processing', '处理中'), ('completed', '已完成'), ('failed', '失败')], db_index=True, default='pending', max_length=20, verbose_name='状态')),
                ('result_type', models.CharField(blank=True, choices=[('unchanged', '未调整'), ('adjusted', '已调整'), ('aggregated', '汇总结果'), ('skipped', '跳过')], max_length=20, verbose_name='结果类型')),
                ('reviewed_unit', models.CharField(blank=True, max_length=32, verbose_name='审核单位')),
                ('reviewed_unit_price', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True, verbose_name='审核单价')),
                ('reviewed_quantity', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True, verbose_name='审核数量')),
                ('reviewed_days', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True, verbose_name='审核天数')),
                ('reviewed_amount', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True, verbose_name='审核金额')),
                ('reduction_amount', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True, verbose_name='审减金额')),
                ('reason', models.TextField(blank=True, verbose_name='审减原因')),
                ('evidence_json', models.JSONField(blank=True, default=dict, verbose_name='审核证据')),
                ('error_message', models.TextField(blank=True, verbose_name='错误信息')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('submission_row', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='decision', to='price_audit.priceauditsubmissionrow', verbose_name='所属送审行')),
            ],
            options={
                'verbose_name': '价格审核结果',
                'verbose_name_plural': '价格审核结果',
                'db_table': 'price_audit_row_decision',
                'ordering': ('submission_row__submission_id', 'submission_row__excel_row_no'),
            },
        ),
        migrations.AddConstraint(
            model_name='priceauditsubmissionrow',
            constraint=models.UniqueConstraint(fields=('submission', 'excel_row_no'), name='uniq_price_audit_submission_row_excel_row'),
        ),
    ]
