# Generated by Django 5.2.8 on 2026-03-11 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price_audit', '0005_priceauditsubmission_priceauditsubmissionrow_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='priceauditsubmission',
            name='current_message',
            field=models.CharField(blank=True, max_length=255, verbose_name='当前进度说明'),
        ),
        migrations.AddField(
            model_name='priceauditsubmission',
            name='current_step',
            field=models.CharField(choices=[('queued', '已入队'), ('parsing', '解析中'), ('reviewing', '审核中'), ('aggregating', '汇总中'), ('exporting', '导出中'), ('completed', '已完成'), ('failed', '失败')], db_index=True, default='queued', max_length=20, verbose_name='当前阶段'),
        ),
        migrations.AddField(
            model_name='priceauditsubmission',
            name='failed_rows',
            field=models.PositiveIntegerField(default=0, verbose_name='失败行数'),
        ),
        migrations.AddField(
            model_name='priceauditsubmission',
            name='processed_rows',
            field=models.PositiveIntegerField(default=0, verbose_name='已处理明细行数'),
        ),
        migrations.AddField(
            model_name='priceauditsubmission',
            name='progress_percent',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='进度百分比'),
        ),
        migrations.AddField(
            model_name='priceauditsubmission',
            name='total_rows',
            field=models.PositiveIntegerField(default=0, verbose_name='待审核明细行数'),
        ),
    ]
