# Generated by Django 5.2.8 on 2026-03-13 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("price_audit", "0006_priceauditsubmission_current_message_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="priceauditsubmission",
            name="exhibition_center_id",
            field=models.PositiveSmallIntegerField(
                choices=[(0, "天津梅江会展中心"), (1, "天津国家会展中心")],
                default=0,
                verbose_name="会展中心",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="priceauditsubmission",
            name="project_nature",
            field=models.PositiveSmallIntegerField(
                choices=[(0, "临时展会"), (1, "常设陈列")],
                default=0,
                verbose_name="项目性质",
            ),
            preserve_default=False,
        ),
    ]
